name: ReportReborn
version: @version@
main: com.github.zflxw.reportreborn.ReportReborn
api-version: 1.17
authors: [ zFlxw ]
description: ReportReborn is an improved rework of my former plugin "report".
